version: "3.9"
services:
  database:
    build: ./database
    ports:
      - "3307:3306"
    networks:
      my_network:
        ipv4_address: 172.18.0.2
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 1s
      timeout: 5s
      retries: 50

  django:
    build: .
    ports:
      - "8000:8000"
    networks:
      my_network:
        ipv4_address: 172.18.0.3
    depends_on:
      database:
        condition: service_healthy
    restart: always

networks:
  my_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
